"""add anomaly detection columns to telemetry

Revision ID: 86ebda99a60c
Revises: 
Create Date: 2026-07-09 11:39:23.124833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ebda99a60c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('anomaly_score', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('is_anomaly', sa.Boolean(), nullable=True))
    op.add_column('telemetry', sa.Column('model_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_telemetry_anomaly_score'), 'telemetry', ['anomaly_score'], unique=False)
    op.create_index(op.f('ix_telemetry_is_anomaly'), 'telemetry', ['is_anomaly'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_is_anomaly'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_anomaly_score'), table_name='telemetry')
    op.drop_column('telemetry', 'model_version')
    op.drop_column('telemetry', 'is_anomaly')
    op.drop_column('telemetry', 'anomaly_score')
    # ### end Alembic commands ###
